name: Release
on:
  push:
    tags:
      - "v*"
env:
  MISE_ENV: publish

jobs:
  publish-chrome:
    name: Publish extension to the Chrome Webstore
    runs-on: ubuntu-24.04
    env:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        run: mise run zip:chrome

      - name: Publish
        run: mise run publish:chrome

  publish-firefox:
    name: Publish extension to the Firefox add-ons
    runs-on: ubuntu-24.04
    env:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        run: mise run zip:firefox

      - name: Publish
        run: mise run publish:firefox
