name: Schedule
on:
  schedule:
    - cron: "25 14 * * *"
env:
  MISE_ENV: ci
jobs:
  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          - "gitlab-v1"
          - "gitlab-v2"
          - "github-v1"
          - "github-v2"
    env:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup
        uses: ./.github/actions/setup

      - name: Setup Playwright
        uses: ./.github/actions/setup-playwright

      - name: Dump GitLab cookies
        if: ${{ startsWith(matrix.project, 'gitlab-') }}
        run: mise exec -- op read --out-file "tests/e2e/playwright/.auth/user-${{ matrix.project }}.json" "op://Conventional comments/GitLab ${{ matrix.project == 'gitlab-v1' && 'V1' || 'V2' }}/cookies"

      - name: Build
        run: mise run build

      - name: Run Playwright tests
        run: mise run test:e2e -- --project ${{ matrix.project }}

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-e2e-${{ matrix.project }}
          path: |
            playwright-report/
            playwright-videos/
            test-results/
          retention-days: 30
